<?php include_once '../scripts/mockupFunctions.php' ?>
<?php include_once '../scripts/globalVariables.php' ?>
<?php 
	$navPrevious = "#";
	$navNext = "#";
	$showModuleProgress = 1;
	$pageTitle = "#.# Topic Name";
	
	$breadCrumbs = array(
		array("url"=>"../index.php", "displayTitle"=>"Home"),
		array("url"=>"../index.php", "displayTitle"=>"#. Module Name Here"),
		array("url"=>"", "displayTitle"=>$pageTitle));
?>

<!doctype html>
<html>
	<head>
		<?php writeHead($pageTitle); ?>
		<script>$(document).ready(function(){$.ajax({url: "json/kitten.json"}).done(function(obj) {setTop(obj);});});</script>
	</head>
	
	<body>
		<?php writeTop($navNext, $navPrevious, $showModuleProgress, $breadCrumbs); ?>
	
		<div class="contentWrapper" id="contentWrapper">
			<h2><?php echo $pageTitle ?></h2>
			<p>In this topic you will learn about</p>
			List goes here
			
			
			<mark>This page will be automatically generated by PLE as the current version of PLE
			does not have a topic landing page.
			
			</mark>
			
			
			
			
			
			<footer><?php writeFooter() ?></footer>
		</div>
	</body>
</html>